services:

  nginx:
    image: nginx:1.27.0-alpine
    container_name: nginx_app_1
    depends_on:
      - fastapi
      #- frontend
    ports:
      - "80:80"
      #- "443:443"
    environment:
      - NGINX_HOST=${DOMAIN}
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ./app_logs/nginx:/var/log/nginx  # Логи nginx
    networks:
      - app-network

  postgres:
    image: postgres:18.1-bookworm
    container_name: postgres_1
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${pswd}
    volumes:
      - ./postgresql/data:/var/lib/postgresql
      - ./app_logs/postgres:/var/log/postgresql  # Логи PostgreSQL
    ports:
      #- "127.0.0.1:5432:5432"
      - 5432:5432
    networks:
      - app-network
  
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      #- "6379:6379"
      - "127.0.0.1:6379:6379"
    volumes:
      - ./redis_data:/data
      # - ./app_logs/redis:/var/log/redis  # Добавляем, если redis настроен писать логи в файл
    environment:
      - REDIS_PASSWORD=${pswd}  # пароль из .env
    command: [ "redis-server", "--requirepass", "${pswd}" ]
    restart: unless-stopped
    networks:
      - app-network

  fastapi:
    build: ./app
    container_name: fastapi_1
    volumes:
      - ./app:/data/app
      - ./app_logs/fastapi:/etc/loggs/fastapi # Добавляем том для логов FastAPI
      - ./uploads:/data/uploads
    env_file:
      - .env
    ports:
      - "127.0.0.1:8000:8000"
      #- "8000:8000"
    depends_on:
      - postgres
      - elasticsearch
    networks:
      - app-network

  frontend:
    build: ./front
    container_name: frontend
    ports:
      #- "127.0.0.1:5173:5173"
      - "5173:5173"
    # environment:
      # - API_URL = http://${DOMAIN}/api

    networks:
      - app-network

  elasticsearch:
    image: elasticsearch:9.1.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false # Отключаем SSL
      - ELASTIC_PASSWORD=${pswd}
      - network.host=0.0.0.0
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"  
      - "9300:9300" 
    networks:
      - app-network

  kibana:
    image: kibana:9.1.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200 # Указываем на наш Elasticsearch
      # docker exec -it elasticsearch /usr/share/elasticsearch/bin/elasticsearch-service-tokens create elastic/kibana kibana-token
      - ELASTICSEARCH_SERVICEACCOUNTTOKEN=AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS10b2tlbjp6RVN2UmlOSFJsZTZFR3JTQTVJeEFn
    ports:
      - "5601:5601"                         # Порт для веб-интерфейса Kibana
    depends_on:
      - elasticsearch
    networks:
      - app-network
  

volumes:
  elasticsearch-data:

networks:
  app-network:
    driver: bridge