"""инициализация

Revision ID: 18be7b3bcf58
Revises: 
Create Date: 2026-09-21 11:38:31.899885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18be7b3bcf58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('elektronnyj_prajs_list_novyj_versija3_p1')
    op.drop_table('dm_product_1')
    op.add_column('requests', sa.Column('end_customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'requests', 'customers', ['end_customer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_column('requests', 'end_customer_id')
    op.create_table('dm_product_1',
    sa.Column('param_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('values', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('matched_rows', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('elektronnyj_prajs_list_novyj_versija3_p1',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ustrojstvo_prinuditel_nogo_otkrytija', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tip_uplotnenija', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tip_konstruktsii', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nominal_nyj_diametr_vhodnoj_mm', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nominal_nyj_diametr_vyhodnoj_mm', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nominal_noe_davlenie_vhodnoe_kgs_sm', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nominal_noe_davlenie_vyhodnoe_kgs_sm', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('klimaticheskoe_ispolnenie', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('temperatura_rabochej_sredy_minimal_naja_c', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('temperatura_rabochej_sredy_maksimal_naja_c', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tip_prisoedinenija_k_truboprovodu', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('flantsevoe_ispolnenie', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tip_uplotnenija_zatvora', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('material_korpusa', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('material_kryshki_kolpaka_i_napravljajuschej_vtulki', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('material_zolotnika_i_sedla', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('po_sposobu_sbrosa_rabochej_sredy', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ispytanija', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pokraska', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ploschad_sedla_mm', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('koef_rashoda_gaza_1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('koef_rashoda_zhidkosti_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vysota_h_mm', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stroitel_naja_dlina_l1_mm', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stroitel_naja_dlina_l2_mm', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('massa_kg', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nalichie_kof', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nalichie_zip', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('markirovka', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tsena_sht_rub_bez_nds', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tsena_sht_rub_s_nds_22', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('elektronnyj_prajs_list_novyj_versija3_p1_pkey'))
    )
    # ### end Alembic commands ###
