KEY_MAPPING = {
    "Email Заказчика": "email_customer",
    "Адрес Заказчика": "address_customer",
    "Должность Заказчика": "position_customer",
    "Испытания": "tests",
    "Климатическое исполнение": "climate_version",
    "Комментарий": "comment",
    "Маркировка": "marking",
    "Материал корпуса": "body_material",
    "Наличие ЗИП": "has_spare_parts",
    "Наличие КОФ": "has_cof",
    "Номинальное давление входное, кгс/см²": "nominal_pressure_inlet",
    "Номинальное давление выходное, кгс/см²": "nominal_pressure_outlet",
    "Номинальный диаметр входной, мм": "nominal_diameter_inlet",
    "Номинальный диаметр выходной, мм": "nominal_diameter_outlet",
    "Организация Заказчика": "organization_customer",
    "По способу сброса рабочей среды": "discharge_method",
    "Покраска": "painting",
    "Проектная организация": "design_organization",
    "Телефон Заказчика": "phone_customer",
    "Температура рабочей среды максимальная, °C": "max_working_temperature",
    "Температура рабочей среды минимальная, °C": "min_working_temperature",
    "Тип конструкции": "design_type",
    "Тип присоединения к трубопроводу": "connection_type",
    "Тип уплотнения": "seal_type",
    "Тип уплотнения затвора": "gate_seal_type",
    "Устройство принудительного открытия": "forced_opening_device",
    "ФИО Заказчика": "fio_customer",
    "Фланцевое исполнение": "flange_version",
    "Цена /шт. руб без НДС": "price_without_vat",
    "Цена /шт. руб с НДС 22%": "price_with_vat",
    "Чертеж": "drawing_url",
    "дата": "date",
    "номер_запроса": "request_number",
    "адрес_исполнителя": "executor_address",
    "телефон_исполнителя": "executor_phone",
    "email_исполнителя": "executor_email",
    "фио_исполнителя": "executor_fio",
    "должность_исполнителя": "executor_position",
    "id": "id"
}